name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile eng CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.eng.tex
      - name: Compile rus CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.rus.tex
      - name: Prepare deploy data
        run: |
          mkdir data
          cp cv.eng.pdf data/
          cp cv.rus.pdf data/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: compiled-${{ github.ref_name }}
          folder: data
